# Generated by Django 4.1.2 on 2022-12-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='TeacherModel',
        ),
    ]
